library(ggplot2)

#' @title bin_cumulative
#' @description adds a column of cumulative probability to the data frame generated by bin_distribution
#' @param trials: total number of trials
#' @param prob: probability of success
#' @return data.frame of success, probability, and cumulative probability
#' @export
#' @examples
#' bin_cumulative(trials = 5, prob = 0.5)
bin_cumulative<-function(trials,prob){
  bin_dist<-bin_distribution(trials,prob)
  cum<-c()
  for (i in c(1:length(bin_dist$probability))){
    if (i==1){
      cum[i]<-bin_dist$probability[i]
    } else{
      cum[i]<-cum[i-1]+bin_dist$probability[i]
    }
  }
  bin_dist$cumulative<-cum
  class(bin_dist)<-c("bincum","data.frame")
  return(bin_dist)
}

#invisible?

#' @export
plot.bincum<-function(dat){
  ggplot(data=dat, aes(x=success, y=cumulative)) +
    geom_line() +
    geom_point() +
    theme_light()
}
